---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
library(SingleR)
library(scater)
library(MuSiC)
library(BisqueRNA)
library(hdf5r)
library(celldex)
library(xbioc)
```


```{r}
#pre-processing the data
#Healthy data
#Donor1.data <- Read10X_h5("GSM3489182_Donor_01_filtered_gene_bc_matrices_h5.h5")
#Donor1 <- CreateSeuratObject(counts = Donor1.data, assay = "RNA", min.cells = 3, project = "Donor1", min.features = 200)
#Donor1@meta.data
#Donor2.data <- Read10X_h5("GSM3489185_Donor_02_filtered_gene_bc_matrices_h5.h5")
#Donor2 <- CreateSeuratObject(counts = Donor2.data, assay = "RNA", project = "Donor2", min.cells = 3, min.features = 200 )
Donor3.data <- Read10X_h5("GSM3489187_Donor_03_filtered_gene_bc_matrices_h5.h5")
Donor3 <- CreateSeuratObject(counts = Donor3.data, assay = "RNA", min.cells = 3, project = "Donor3", min.features = 200)
#Donor4.data <- Read10X_h5("GSM3489189_Donor_04_filtered_gene_bc_matrices_h5.h5")
#Donor4 <- CreateSeuratObject(counts = Donor4.data, assay = "RNA", min.cells = 3, project = "Donor4", min.features = 200)
#Donor5.data <- Read10X_h5("GSM3489191_Donor_05_filtered_gene_bc_matrices_h5.h5")
#Donor5 <- CreateSeuratObject(counts = Donor5.data, assay = "RNA", min.cells = 3, min.features = 200)
Donor6.data <- Read10X_h5("GSM3489193_Donor_06_filtered_gene_bc_matrices_h5.h5")
Donor6 <- CreateSeuratObject(counts = Donor6.data, assay = "RNA", min.cells = 3, min.features = 200)
#Donor7.data <- Read10X_h5("GSM3489195_Donor_07_filtered_gene_bc_matrices_h5.h5")
#Donor7 <- CreateSeuratObject(counts = Donor7.data, assay = "RNA", min.cells = 3, min.features = 200)
Donor8.data <- Read10X_h5("GSM3489197_Donor_08_filtered_gene_bc_matrices_h5.h5")
Donor8 <- CreateSeuratObject(counts = Donor8.data, assay = "RNA", min.cells = 3, min.features = 200)



#merging datasets
Reyfman <- merge(Donor3, y = c(Donor6, Donor8))
Reyfman@meta.data
#ReyfmanIntIPF <- merge(IPF1, y =c(IPF2, IPF3, IPF4))
#ReyfmanIntIPF@meta.data
#Reyfman <- merge(ReyfmanIntHealthy, y = c(ReyfmanIntIPF))
#Reyfman@meta.data
```

```{r}
#Suerat Standard Workflow 
Reyfman <- NormalizeData(Reyfman)
Reyfman <- FindVariableFeatures(Reyfman, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(Reyfman)
Reyfman <- ScaleData(Reyfman, features = all.genes)
Reyfman <- RunPCA(Reyfman)
Reyfman <- FindNeighbors(Reyfman, dims= 1:10)
Reyfman <- FindClusters(Reyfman, resolution = 0.5)
Reyfman <- RunTSNE(Reyfman)
#TSNEPlot(Reyfman, reduction = "tsne")


#SingleR
ReyfmanSC <- as.SingleCellExperiment(Reyfman)
ReyfmanSC <- logNormCounts(ReyfmanSC)
ReyfmanSC
Encode <- celldex::BlueprintEncodeData()
pred.ReyfmanSC <- SingleR(test = ReyfmanSC, ref = Encode, labels = Encode$label.main)
Reyfman[["SingleR.labels"]] <- pred.ReyfmanSC$labels
#table(pred.ReyfmanSC$labels)
#TSNEPlot(Reyfman, label = FALSE, pt.size = 0.5, group.by = "SingleR.labels")


#expression data
exprs <- as.matrix(read.csv("fgtex.lung.ncounts.genesymbol.csv", header = TRUE, row.names = 1))
#phenotype data
pData <- read.csv("fgtex.lung.sample.info.csv", header = TRUE, row.names = 1)
#all(rownames(pData)==colnames(exprs))
metadata <- data.frame(labelDescription = 
                         c("Sex",
                           "Age",
                           "Decade",
                           "Death",
                           "Batch"),
                       row.names = c("Sex", "Age", "Decade", "Death", "Batch"))
phenoData <- new("AnnotatedDataFrame",
                 data = pData, varMetadata = metadata)

#construct ExpressionSet
bulkexp <- ExpressionSet(assayData = exprs, phenoData = phenoData)

#sc expression set
Reyfman@meta.data
Reyfmanpheno <- Reyfman@meta.data
ReyfmanMtx <- Reyfman[["RNA"]]@counts
ReyfmanMtx <- as.matrix(ReyfmanMtx)
scexp <- ExpressionSet(ReyfmanMtx, phenoData=annotatedDataFrameFrom(ReyfmanMtx, byrow=FALSE))
phenoData(scexp) <- AnnotatedDataFrame(Reyfmanpheno)
Deconv <- music_prop(bulk.eset = bulkexp, sc.eset = scexp, clusters = 'SingleR.labels', samples = 'orig.ident')
```

```{r}
# pval func
stat_smooth_func_with_pval <- function(mapping = NULL, data = NULL,
                                            geom = "smooth", position = "identity",
                                            ...,
                                            method = "auto",
                                            formula = y ~ x,
                                            se = TRUE,
                                            n = 80,
                                            span = 0.75,
                                            fullrange = FALSE,
                                            level = 0.95,
                                            method.args = list(),
                                            na.rm = FALSE,
                                            show.legend = NA,
                                            inherit.aes = TRUE,
                                            xpos = NULL,
                                            ypos = NULL,
                                            xpos2 = NULL,
                                            ypos2 = NULL) {
  layer(
    data = data,
    mapping = mapping,
    stat = StatSmoothFunc,
    geom = geom,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      method = method,
      formula = formula,
      se = se,
      n = n,
      fullrange = fullrange,
      level = level,
      na.rm = na.rm,
      method.args = method.args,
      span = span,
      xpos = xpos,
      ypos = ypos,
      xpos2 = xpos2,
      ypos2 = ypos2,
      ...
    )
  )
}

StatSmoothFunc <- ggproto("StatSmooth", Stat,
                          
                          setup_params = function(data, params) {
                            # Figure out what type of smoothing to do: loess for small datasets,
                            # gam with a cubic regression basis for large data
                            # This is based on the size of the _largest_ group.
                            if (identical(params$method, "auto")) {
                              max_group <- max(table(data$group))
                              
                              if (max_group < 1000) {
                                params$method <- "loess"
                              } else {
                                params$method <- "gam"
                                params$formula <- y ~ s(x, bs = "cs")
                              }
                            }
                            if (identical(params$method, "gam")) {
                              params$method <- mgcv::gam
                            }
                            
                            params
                          },
                          
                          compute_group = function(data, scales, method = "auto", formula = y~x,
                                                   se = TRUE, n = 80, span = 0.75, fullrange = FALSE,
                                                   xseq = NULL, level = 0.95, method.args = list(),
                                                   na.rm = FALSE, xpos=NULL, ypos=NULL, 
                                                   xpos2=NULL, ypos2=NULL) {
                            if (length(unique(data$x)) < 2) {
                              # Not enough data to perform fit
                              return(data.frame())
                            }
                            
                            if (is.null(data$weight)) data$weight <- 1
                            
                            if (is.null(xseq)) {
                              if (is.integer(data$x)) {
                                if (fullrange) {
                                  xseq <- scales$x$dimension()
                                } else {
                                  xseq <- sort(unique(data$x))
                                }
                              } else {
                                if (fullrange) {
                                  range <- scales$x$dimension()
                                } else {
                                  range <- range(data$x, na.rm = TRUE)
                                }
                                xseq <- seq(range[1], range[2], length.out = n)
                              }
                            }
                            # Special case span because it's the most commonly used model argument
                            if (identical(method, "loess")) {
                              method.args$span <- span
                            }
                            
                            if (is.character(method)) method <- match.fun(method)
                            
                            base.args <- list(quote(formula), data = quote(data), weights = quote(weight))
                            model <- do.call(method, c(base.args, method.args))
                            
                            m = model
                            eq1 <- substitute(italic(y) == a + b %.% italic(x), 
                                              list(a = format(coef(m)[[1]], digits = 3), 
                                                   b = format(coef(m)[[2]], digits = 3)))
                            
                            eq2 <- substitute(italic(r)^2~"="~r2*","~~italic(p)~"="~pval, 
                                              list(r2 = format(summary(m)$r.squared, digits = 3),
                                                   pval = format(summary(m)$coef[2,4], digits = 3)))
                            
                            func_string1 = as.character(as.expression(eq1))
                            func_string2 = as.character(as.expression(eq2))
                            
                            if(is.null(xpos)) xpos = min(data$x)*0.9
                            if(is.null(ypos)) ypos = max(data$y)*1
                            if(is.null(xpos2)) xpos2 = xpos
                            if(is.null(ypos2)) ypos2 = max(data$y)*0.95
                            
                            data.frame(x = rbind(xpos, xpos2), 
                                       y = rbind(ypos, ypos2), 
                                       label = rbind(func_string1, func_string2))
                            
                          },
                          
                          required_aes = c("x", "y")
)
```

```{r}
# plot
wp <- read.csv("Habermann.prop.weighted.csv", header = TRUE, row.names = 1)
#celltype_list <- colnames(wp)[-length(colnames(wp))]
celltype_list <- colnames(wp)[-1]
for (i in seq_along(celltype_list)) {
  wpp <- wp[celltype_list[i]]
  wpp <- mutate(wpp, wp$Age)
  p <- ggplot(wpp, aes_string(x = wp$Age, y = celltype_list[i])) +
    geom_point(position = position_jitter(w = 0.1, h = 0),
               color = "black", 
               size = 2) +
    geom_smooth(method = "lm",
                color = "black") +
    theme_classic() +
    ggtitle(celltype_list[i]) +
    xlab("Age") +
    ylab("Proportion") +
    theme(plot.title = element_text(hjust = 0.5, family = "Arial", face = "bold", size = 25),
          axis.text = element_text(size = 20, family = "Arial"),
          axis.title = element_text(size = 20, family = "Arial")) +
    stat_smooth_func_with_pval(geom = "text", method = "lm", hjust = 0, parse = TRUE, size = 4)
  ggsave(p, file = paste0("Habermann.", celltype_list[i], ".png"), width = 15, height = 15, units = "cm")
}
```

```{r}
# plot gtex
wp <- read.csv("Habermann.gtex.weighted.csv", header = TRUE, row.names = 1)
#celltype_list <- colnames(wp)[-length(colnames(wp))]
celltype_list <- colnames(wp)[-1]
wp$Age <- as.factor(wp$Age)
for (i in seq_along(celltype_list)) {
  wpp <- wp[celltype_list[i]]
  wpp <- mutate(wpp, wp$Age)
  p <- ggplot(wpp, aes_string(x = wp$Age, y = celltype_list[i])) +
    geom_boxplot() +
    theme_classic() +
    ggtitle(paste0("GTEx ",celltype_list[i])) +
    theme(plot.title = element_text(hjust = 0.5, size = 20, family = "Arial", face = "bold"),
        axis.text = element_text(size = 15, family = "Arial"),
        axis.title = element_text(size = 15, family = "Arial", face = "bold")) +
   geom_jitter(width = 0.1, aes(color = wp$Age)) +
  stat_compare_means(method = "t.test",
                     label = "p.format",
                     label.x.npc = "center",
                     label.y.npc = "bottom")
  #p.signif for only significance level
  ggsave(p, file = paste0("test", celltype_list[i], ".png"), width = 15, height = 15, units = "cm")
}
```
